### ISSUE TITLE
Increase processing and search accuracy.

### ISSUE THREAD

**Issue by medanisjbara** [medanisjbara/autoemploi-fsm#4]
It can be noted that some results are not found when they clearly do exist in the fetched document. This is due to the inaccuracy of doing OCR on a document obtained from a scanner.  
To fix this, several key steps need to be implemented.
### Tasks
- [ ] #5
- [ ] Do advanced searching to match the maximum number of characters in case of not having a match.
- [ ] Output the names and some information of the target in case of mixed information.
- [ ] Use a set of pre-defined CIN numbers to lower the chances of finding wrong input.
